name: 'Determine tags'
description: "Determines the tag that we are running against (or uses a default). A full checkout must have been done!"
inputs:
  default_tag:
   description: "Default tag to return if we are not sitting at a tag git ref"
   required: true
outputs:
  package_version:
    description: "The package version discovered looking at tags or the default"
    value: steps.determine.outputs.package_version
runs:
  using: "composite"
  steps:
    - name: Determine tag
      id: determine
      shell: "bash"
      run: |
        TAG_NAME=$(git describe --tags --exact-match 2>/dev/null || echo ${{ inputs.default_tag }})
        echo "package_version=$TAG_NAME" >> $GITHUB_OUTPUT
        echo $TAG_NAME
        echo ${{ inputs.default_tag }}