name: 'Build Type Package'
description: 'Builds a type package given a few tags'
inputs:
  func_adl_servicex_type_generator_version:
    description: 'Version of func_adl_servicex_type_generator'
    required: true
  func_adl_types_atlas_version:
    description: 'Version of func_adl_types_atlas'
    required: true
  python_package_base_version:
    description: 'Version of the python package'
    required: true
  release_version:
    description: "Tag of ATLAS container to build the type files from"
    required: true
  push_to_pypi:
    description: "Push to pypi - set to true. Default is false"
    required: false
    default: ''
  PYPI_TOKEN:
    description: "Token to push to pypi"
    required: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies for Base Package
      shell: bash
      run: |
        pip install -e .
    - name: Install func_adl_servicex_type_generator
      uses: actions/checkout@v4
      with:
        repository: gordonwatts/func_adl_servicex_type_generator
        ref: ${{ env.func_adl_servicex_type_generator_version }}
        path: func_adl_servicex_type_generator
    - name: Install func-adl-types-atlas
      uses: actions/checkout@v4
      with:
        repository: gordonwatts/func-adl-types-atlas
        ref: ${{ env.func_adl_types_atlas_version }}
        path: func-adl-types-atlas
    - name: Install dependencies for sub-packages
      shell: bash
      run: |
        cd func_adl_servicex_type_generator
        pip install -e .
        cd ..
        cd func-adl-types-atlas
        pip install -e .
    - name: Cache Type YAML Files
      id: cache-type-yaml
      uses: actions/cache/restore@v3
      with:
        path: cache/yaml
        key: type-yaml-${{ inputs.release_version }}-${{ env.func_adl_types_atlas_version }}
    - name: Build YAML Type File
      shell: bash
      run: |
        atlas_release_type_builder yaml --command_location . --type_json ./cache/yaml ${{ inputs.release_version }}
    - name: Save type yaml file to cache
      uses: actions/cache/save@v3
      with:
        path: cache/yaml
        key: ${{ steps.cache-type-yaml.outputs.cache-primary-key }}
    - name: Build Python Package
      shell: bash
      run: |
        atlas_release_type_builder build --command_location . --type_json ./cache/yaml --type_package ./cache/package  --package_version ${{ inputs.python_package_base_version }} ${{ inputs.release_version }}
    - name: Save Python Package
      uses: actions/upload-artifact@v4
      with:
        name: func_adl_xaod-${{ inputs.python_package_base_version }}-${{ inputs.release_version }}
        path: cache/package/${{ inputs.release_version }}
    - name: Publish to PyPi with Hatch
      if: ${{ inputs.push_to_pypi }}
      shell: bash
      run: |
        pip install hatch
        cd ./cache/package/${{ inputs.release_version }}
        hatch build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./cache/package/${{ inputs.release_version }}
