name: 'Build Type Package'
description: 'Builds a type package given a few tags'
inputs:
  func_adl_servicex_type_generator_version:
    description: 'Version of func_adl_servicex_type_generator'
    required: true
  func_adl_types_atlas_version:
    description: 'Version of func_adl_types_atlas'
    required: true
  python_package_base_version:
    description: 'Version of the python package'
    required: true
  release_version:
    description: "Tag of ATLAS container to build the type files from"
    required: true
runs:
  using: "composite"
  steps:
   run: |
     echo ${{ inputs.func_adl_servicex_type_generator_version }}
     echo ${{ inputs.func_adl_types_atlas_version }}
     echo ${{ inputs.python_package_base_version }}
     echo ${{ inputs.release_version }}
