name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        default: "24.2.12"
  release:
    types: [created]

# These should be set to the latest versions of everything.
env:
  func_adl_servicex_type_generator_version: "v1.1.0"
  func_adl_types_atlas_version: "v1.1.0"

jobs:
  build-single-package:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      release_version: ${{ github.event.inputs.release_version }}
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag ID
        id: determine-tag
        uses: ./.github/actions/determine-tag
        with:
          default_tag: 2.0.0a1
      - name: Build Package
        uses: ./.github/actions/build-types
        with:
          release_version: ${{ github.event.inputs.release_version }}
          func_adl_servicex_type_generator_version: $func_adl_servicex_type_generator_version
          func_adl_types_atlas_version: $func_adl_types_atlas_version
          python_package_base_version: "${{ steps.determine-tag.outputs.package_version }}"

  build-all-packages:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    strategy:
      matrix:
        # release_version: ["21.2.231", "22.2.107"]
        # release_v_number: ["21", "22"]
        include:
          - release_version: "21.2.231"
            release_v_number: "21"
          - release_version: "22.2.107"
            release_v_number: "22"
    environment:
      name: pypi
      url: "https://pypi.org/p/func_adl_servicex_xaodr${{ matrix.release_v_number }}"
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Tag ID
        id: determine-tag
        uses: ./.github/actions/determine-tag
        with:
          default_tag: 2.0.0a1
      - name: Build Package
        uses: ./.github/actions/build-types
        with:
          release_version: ${{ matrix.release_version }}
          func_adl_servicex_type_generator_version: $func_adl_servicex_type_generator_version
          func_adl_types_atlas_version: $func_adl_types_atlas_version
          python_package_base_version: "${{ steps.determine-tag.outputs.package_version }}"
      - name: Build distributions
        shell: bash
        run: |
          cd ./cache/package/${{ matrix.release_version }}
          uvx --from build pyproject-build .
          ls -lhtra dist
      - name: Verify distributions
        shell: bash
        run: |
          cd ./cache/package/${{ matrix.release_version }}
          uvx twine check --strict dist/*
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./cache/package/${{ matrix.release_version }}/dist
          print-hash: true
