name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        default: "24.2.12"
      func_adl_servicex_type_generator_version:
        description: "func_adl_servicex_type_generator github tag"
        required: true
        default: "v1.0b1"
      func_adl_types_atlas_version:
        description: "func_adl_types_atlas github tag"
        required: true
        default: "v1.0.0b1"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Install func_adl_servicex_type_generator
        uses: actions/checkout@v2
        with:
          repository: gordonwatts/func_adl_servicex_type_generator
          ref: ${{ github.event.inputs.func_adl_servicex_type_generator_version }}
          path: func_adl_servicex_type_generator
      - name: Install func-adl-types-atlas
        uses: actions/checkout@v2
        with:
          repository: gordonwatts/func-adl-types-atlas
          ref: ${{ github.event.inputs.func_adl_types_atlas_version }}
          path: func_adl_types_atlas
      - name: Install dependencies
        run: |
          pwd
          ls -R | % {$_.Name}
          cd func_adl_servicex_type_generator
          pip install -e .
      - name: Cache Type YAML Files
        id: cache-type-yaml
        uses: actions/cache@v3
        with:
          path: cache/yaml
          key: type-tyaml-${{ github.event.inputs.release_version }}-${{ github.event.inputs.func_adl_types_atlas_version }}
      - name: Build YAML Type File
        run: |
          atlas_release_type_builder build --command_location . --type_json ./cache/yaml --type_package ./cache/package ${{ github.event.inputs.release_version }}
          ls -R cache
      - name: Save Python Package
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: cache/package
