name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        default: "24.2.12"
      push_to_pypi:
        description: "Push Final Python Package to PyPi"
        required: true
        type: boolean
        default: false
  release:
    types: [created]

# These should be set to the latgest versions of everything.
env:
  func_adl_servicex_type_generator_version: "v1.0.0b6"
  func_adl_types_atlas_version: "v1.0.0b25"

jobs:
  build-single-package:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      release_version: ${{ github.event.inputs.release_version }}
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag ID
        id: determine-tag
        uses: ./.github/actions/determine-tag
        with:
          default_tag: 2.0.0a1
      - name: Build Package
        uses: ./.github/actions/build-types
        with:
          release_version: ${{ github.event.inputs.release_version }}
          func_adl_servicex_type_generator_version: $func_adl_servicex_type_generator_version
          func_adl_types_atlas_version: $func_adl_types_atlas_version
          python_package_base_version: "${{ steps.determine-tag.outputs.package_version }}"
          push_to_pypi: ${{ github.event.inputs.push_to_pypi }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  build-all-packages:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_version: ["21.2.231", "22.2.107"]
    steps:
      - name: Checkout package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag ID
        id: determine-tag
        uses: ./.github/actions/determine-tag
        with:
          default_tag: 2.0.0a1
      - name: Build Package
        uses: ./.github/actions/build-types
        with:
          release_version: ${{ matrix.release_version }}
          func_adl_servicex_type_generator_version: $func_adl_servicex_type_generator_version
          func_adl_types_atlas_version: $func_adl_types_atlas_version
          python_package_base_version: "${{ steps.determine-tag.outputs.package_version }}"
          push_to_pypi: true
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
